### ISSUE TITLE
Rust with web rcon enabled

### ISSUE THREAD

**Issue by gdepre** [gorcon/rcon-cli#12]
using command ./rcon -t web -a x.x.x.x:28017 -p password the result is 'not implemented'

Command is sent from the server hosting the rust dedicated server

**Comment by outdead** [comment]
Set the command with `-c` flag. It runs command in single mode. Execute without commands in interactive mode is not implemented yet.

```./rcon -t web -a x.x.x.x:28017 -p password -c players```

**Comment by gdepre** [comment]
working with `-c` flag.
how to implement commands like `inventory.giveid "SteamID" "short name" "amount"` containing double quotes ?

**Comment by outdead** [comment]
Try to escape qutes with backslash
```
./rcon -t web -a x.x.x.x:28017 -p password -c "inventory.giveid \"SteamID\" \"short name\" \"amount\""
```
Single quote enclosing should also work
```
./rcon -t web -a x.x.x.x:28017 -p password -c 'inventory.giveid "SteamID" "short name" "amount""
```
As far as I can see, not all commands in Rust give a response. `inventory.giveid` same as `say` command is one of them.

I checked qutes with command ban and it works
```
./rcon -e rustlocal -c 'ban "unezisting player" "command testing"'
Player not found
```

**Comment by outdead** [comment]
Interactive mode vaw added in [v0.8.0-beta.2](https://github.com/gorcon/rcon-cli/releases/tag/v0.8.0-beta.2)

Now you can use `./rcon -t web -a x.x.x.x:28017 -p password` without command and type them in terminal window. Please check it.

**Comment by gdepre** [comment]
working with 0.8.0 beta 2
