### ISSUE TITLE
cli: websocket: authentication failed

### ISSUE THREAD

**Issue by D0br0sh4n** [gorcon/rcon-cli#15]
Hi.
1. I build rcon-cli on my macOS 10.15.7 (Catalina)
2. Connect my RUST server: `./rcon-cli -a ip:port -p pass -t web`
3. In server rust config enable rconweb (rconweb="1")
4. I get an error: **cli: websocket: authentication failed**

When i change rconweb="0" (in my RUST server conf) and write command:
`./rcon-cli -a ip:port -p pass -t rcon`, rcon-cli work normaly.

How to make it work with rconweb="1"?
![screen](https://user-images.githubusercontent.com/17463095/117621445-4d8aca80-b17a-11eb-8deb-a719ba9f18c4.png)

**Comment by outdead** [comment]
Hi! Thanks for request. 

Is your server running in Docker?

**Comment by outdead** [comment]
Sorry for the late answer. I checked on my server and it works. Please try the new version https://github.com/gorcon/rcon-cli/releases/tag/v0.10.0
