### ISSUE TITLE
cannot connect with my rust server with +rcon.web "1"

### ISSUE THREAD

**Issue by Owned67** [gorcon/rcon-cli#19]
`rcon.exe -a MYIP:28015 -p MyRconPassword -t web
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x54f9c9]

goroutine 1 [running]:
github.com/gorcon/websocket.(*Conn).Close(0x0, 0xc0000a6f80, 0xc00014e120)
        /media/pk/hdd/projects/repos/github.com/gorcon/rcon-cli/vendor/github.com/gorcon/websocket/websocket.go:122 +0x29
github.com/gorcon/rcon-cli/internal/executor.(*Executor).Close(0xc0000ec3c0, 0x7, 0xc0000d7e88)
        /media/pk/hdd/projects/repos/github.com/gorcon/rcon-cli/internal/executor/executor.go:261 +0x42
github.com/gorcon/rcon-cli/internal/executor.(*Executor).Run(0xc0000ec3c0, 0xc0000e0000, 0x7, 0x8, 0x6bb920, 0xc0000a6f80)
        /media/pk/hdd/projects/repos/github.com/gorcon/rcon-cli/internal/executor/executor.go:81 +0x165
main.main()
        /media/pk/hdd/projects/repos/github.com/gorcon/rcon-cli/main.go:17 +0x16b`

we use +rcon.web" "1", possible to have a fix please?

**Comment by outdead** [comment]
Thanks for your issue. 

It looks like connection error for the server but gorcon panics and cannot display it. Please try https://github.com/gorcon/rcon-cli/releases/tag/v0.10.1 version. I fix program panic and now you should receive a more informative message after launch.

**Comment by Owned67** [comment]
rcon.exe -a MYIP:28015 -p MyRconPassword -t web
`cli: auth: webrcon: dial tcp MYIP:28015: connectex: No connection could be made because the target machine actively refused it`

**Comment by outdead** [comment]
It looks like the problem is solved for `gorcon`, thank you! 

Now you need to find your problem on the server or in the firewall. There is a good tread about this on [stackoverflow](https://stackoverflow.com/questions/2972600/no-connection-could-be-made-because-the-target-machine-actively-refused-it). I hope this will help you. I also recommend you to check server with `+rcon.web 0` param.

**Comment by Owned67** [comment]
I don't have access to his server so close :( ^^ thanks for support
