### ISSUE TITLE
V Rising

### ISSUE THREAD

**Issue by MHketbi** [gorcon/rcon-cli#21]
hello,

does this support V Rising?

**Comment by outdead** [comment]
Hi! Unfortunately I don't have V Rising and I don't know. I researched in Google and did not found information about supporting RCON in V Rising. it look like this game doesn't support this protocol.

**Comment by outdead** [comment]
If V Rising supports RCON, then most likely gorcon will be able to work with this game.

**Comment by MHketbi** [comment]
the game supports RCON

https://github.com/StunlockStudios/vrising-dedicated-server-instructions#rcon

**Comment by outdead** [comment]
Feel free to check. I will be grateful if you post your results here.

**Comment by phantomora** [comment]
it does connect to v rising
