### ISSUE TITLE
Windows - Command with double quotes treated as separate commands

### ISSUE THREAD

**Issue by RobertKalnins** [gorcon/rcon-cli#25]
#### Issue: Command with double quotes treated as multiple commands on windows systems
Expected behaviour: 'command "string-for-command"' passes the command with "string-for-command" to rcon server

Experienced behaviour: command is treated by rcon client as multiple separate commands

Not working in Powershell - PSVersion - 5.1.19041.2364
Haven't tested on other versions of powershell.
![image](https://user-images.githubusercontent.com/48470997/211221887-c239e940-dcc9-4b21-a520-346fff9551dc.png)

Not working in cmd:
![image](https://user-images.githubusercontent.com/48470997/211221942-183d056f-2488-4d05-8a4e-0bf8d325e0a2.png)

Working in WSL - Ubuntu:
![image](https://user-images.githubusercontent.com/48470997/211221860-0f35b031-2ec1-43a4-9388-7fbe8d636c15.png)

Also works in my Linux server with no problems

**Comment by outdead** [comment]
I don't have this fiend. But I'll try to check. Thanks for report!

**Comment by outdead** [comment]
Try `.\rcon -c  .\rcon.yaml "servermsg \"Test test test\""`
