### ISSUE TITLE
Crash when entering environment variable

### ISSUE THREAD

**Issue by somethingamajig** [gorcon/rcon-cli#26]
I have been trying for hours now to enter the ./rcon -e zomboid command after editing my .yaml file with all the correct information. Every time I enter it the console just crashes out. No idea why. Only thing I have to go on is that when I type ./rcon -e all by itself it loads the default information, which is empty but it does run and asks for a password, then crashes when I enter.

**Comment by outdead** [comment]
Please try [v0.10.3](https://github.com/gorcon/rcon-cli/releases/tag/v0.10.3).
