### ISSUE TITLE
"rcon.yaml" Does Not Seem To Load By Default

### ISSUE THREAD

**Issue by IanDLacy** [gorcon/rcon-cli#28]
Is there something I'm missing about the default configuration path?

I put it in the current working directory, and it doesn't load it.
I put it in my home folder, and it doesn't load it.
I put it next to the executable, and it doesn't load it.
I made it a dot file, and it doesn't load it.

It seems that feature is just not working?

**Comment by outdead** [comment]
Hi! Thanks for issue. I checked this bug and successfully reproduced it. I will fix it soon.

**Comment by outdead** [comment]
Please try [v0.10.3](https://github.com/gorcon/rcon-cli/releases/tag/v0.10.3).

**Comment by IanDLacy** [comment]
Hey, v0.10.3 works great! Thanks so much!
