### ISSUE TITLE
Working with palworld!... but

### ISSUE THREAD

**Issue by Khyretos** [gorcon/rcon-cli#34]
Hey there, i have not been able to run it on docker due to my lack of exp and a docker-compose file.

but it is working if i use it directly!  my only problem is that i cannot send strings with spaces.
![image](https://github.com/gorcon/rcon-cli/assets/25864917/d9a0b23d-df14-46fc-87fc-0a938cc4a79c)

**Comment by AndreBaumeier** [comment]
you can't even send strings with spaces from within the game. either it needs a special format or its broken - needs a bug report

**Comment by Braste** [comment]
At the moment the Broadcast command cuts the message at the first space, only the Palworld devs can fix this.

**Comment by outdead** [comment]
Hi! I have no Palworld. Do I understand correctly that this is a game bug?

**Comment by Khyretos** [comment]
> Hi! I have no Palworld. Do I understand correctly that this is a game bug?

this is something the devs need to resolve.

**Comment by outdead** [comment]
Can we close issue here?
