### ISSUE TITLE
Does not work with ARK

### ISSUE THREAD

**Issue by antimodes201** [gorcon/rcon-cli#4]
Ark requires the query port as part of the connection as of a few patches ago.

When using this with ARK you will get dial tcp $IP:$PORT: i/o timeout

**Comment by outdead** [comment]
I checked my own ARK server and the commands are works. Provide additional information so that I can reproduce the error.

**Comment by parkervcp** [comment]
While running ark and trying to connect to the server as soon as it opens the port I have found trying to connect while ARK is still getting ready it will give the i/o timeout error.

**Comment by outdead** [comment]
Try to check new version https://github.com/gorcon/rcon-cli/releases/tag/v0.6.0

**Comment by outdead** [comment]
Fixed in v0.6.0

![Screenshot_20200710_150600](https://user-images.githubusercontent.com/26613089/87152952-517e5f80-c2bf-11ea-8c25-f08e90081ee8.png)
