### ISSUE TITLE
[QUESTION] Plugin for Unraid

### ISSUE THREAD

**Issue by ich777** [gorcon/rcon-cli#42]
Hi @outdead,

is it okay for you if I distribute your rcon-cli as a plugin for Unraid so that Unraid users can easily make use of it?
Since I was in search for a new source for a reliable rcon cli client I found your repository, which I actually really like because it's based on golang.

Currently I have a plugin for rcon that is based of another repository, that seems to be not maintained anymore, see my plugin [here](https://github.com/ich777/unraid-rcon).

If you have a PayPal or sponsor link let me know and I'm happy to change the Donation link in the plugin to that.

Cheers,
Christoph

**Comment by outdead** [comment]
Hi! feel free to include.

**Comment by ich777** [comment]
Nice, thank you!
